# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
name: Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ${{matrix.os}}

    strategy:
      matrix:
        os: [macos-13, ubuntu-latest, windows-latest]

    steps:
    - uses: actions/checkout@v4
    - uses: dlang-community/setup-dlang@934047eba531212a2c77e7c1b5999d32c2becb81

    - name: 'Build & Test'
      run: |
        # Build the project, with its main file included, without unittests
        dub build -b release
        
    - name: Upload
      uses: actions/upload-artifact@v4
      with:
        name: build-${{matrix.os}}
        path: ${{github.workspace}}/cac*
